# fly.toml app configuration file generated for amabot on 2023-11-12T17:30:04+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "amabot"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "10s"

[experimental]
  auto_rollback = true

[build]
